### ISSUE TITLE
Documentation should include a warning that it's easy to exhaust file descriptors if lots of subscriptions are used

### ISSUE THREAD

**Issue by scouten** [whatyouhide/redix_pubsub#18]
As the subject line says, if you build a system with a lot of discrete subscriptions, the VM can easily exhaust the file descriptors available to it by having lots of individual TCP/IP connections. This design constraint should, at a minimum, be documented and (ideally) mitigated somehow.

**Comment by whatyouhide** [comment]
I am not sure what you mean by "discrete subscription".

* If you mean a subscription from a process to a channel/pattern through a shared `Redix.PubSub` connection, then you are not opening a file descriptor/TCP connection per subscription. You're only opening one for each `Redix.PubSub` connection.

* if you mean a subscription being a `Redix.PubSub` connection, then yes, opening many of these connections will eventually exhaust file descriptors. This is a constraint in everything that opens a socket connection: the same will happen if you open too many connections to any database (that uses TCP), too many long-living HTTP connections, and so on.

I will not mitigate this in any way. The reason is that the user already has control over the limited resource (TCP connection) because they are the one starting `Redix.PubSub` connections, so they can control how many they start and avoid running out of file descriptors. I might document this, but I don't see how this is specific to `Redix.PubSub` since it's a problem that everything that opens a socket shares.

Hope this clarifies things. Please feel free to comment again if something is not clear 🙃

Thanks for the contribution! 💟
